name: pet_care
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5 # State management
  intl: ^0.18.1 # Date formatting
  table_calendar: ^3.0.9 # Calendar views
  flutter_svg: ^2.0.9 # SVG support
  uuid: ^4.3.2 # For generating unique IDs
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  shared_preferences: ^2.2.1
  # flutter_local_notifications: ^9.9.1
  # timezone: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    # - assets/images/paws.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/pet-care.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/pet-care.png"
