name: pet_care
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5 # State management
  intl: ^0.18.1 # Date formatting
  table_calendar: ^3.0.9 # Calendar views
  flutter_svg: ^2.0.9 # SVG support
  uuid: ^4.3.2 # For generating unique IDs

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
